test: shell script to install deps

diff --git a/.github/workflows/build-linux-arm64.yml b/.github/workflows/build-linux-arm64.yml
--- a/.github/workflows/build-linux-arm64.yml
+++ b/.github/workflows/build-linux-arm64.yml
@@ -83,7 +83,38 @@ jobs:
               git clone --branch ${{ github.event.inputs.tag }} --depth 1 --recursive https://github.com/blender/blender.git
               cd blender
               # make deps
-              python ./build_files/build_environment/install_linux_packages.py --all
+              # run deps install script up to 10 times (if downloads faill)
+              script_to_run="python ./build_files/build_environment/install_linux_packages.py --all"
+
+              # Maximum number of attempts
+              max_attempts=10
+
+              # Current attempt counter
+              attempt=1
+
+              while [ $attempt -le $max_attempts ]
+              do
+                  echo "Attempt $attempt of $max_attempts:"
+                  
+                  # Run the script
+                  $script_to_run
+                  
+                  # Check the exit status of the script
+                  if [ $? -eq 0 ]; then
+                      echo "Script executed successfully on attempt $attempt."
+                      break
+                  else
+                      echo "Script failed on attempt $attempt. Retrying..."
+                  fi
+
+                  # Increment the attempt counter
+                  ((attempt++))
+              done
+
+              if [ $attempt -gt $max_attempts ]; then
+                  echo "Script failed after $max_attempts attempts."
+              fi
+              
 
             fi
           shell: bash
